/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoteResponseDto } from '../../models/note-response-dto';

export interface GetNotes$Params {
  boardId: string;
}

export function getNotes(http: HttpClient, rootUrl: string, params: GetNotes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NoteResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getNotes.PATH, 'get');
  if (params) {
    rb.path('boardId', params.boardId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NoteResponseDto>>;
    })
  );
}

getNotes.PATH = '/api/v1/boards/{boardId}/notes';
