/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoteRequestDto } from '../../models/note-request-dto';
import { NoteResponseDto } from '../../models/note-response-dto';

export interface Patch1$Params {
  boardId: string;
  noteId: string;
      body: NoteRequestDto
}

export function patch1(http: HttpClient, rootUrl: string, params: Patch1$Params, context?: HttpContext): Observable<StrictHttpResponse<NoteResponseDto>> {
  const rb = new RequestBuilder(rootUrl, patch1.PATH, 'patch');
  if (params) {
    rb.path('boardId', params.boardId, {});
    rb.path('noteId', params.noteId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NoteResponseDto>;
    })
  );
}

patch1.PATH = '/api/v1/boards/{boardId}/notes/{noteId}';
