/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangePasswordRequest {
  confirmNewPassword?: string;
  currentPassword?: string;
  newPassword?: string;
}
