/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LinkResponse {
  boardId?: string;
  createdDate?: string;
  fromNoteId?: string;
  id?: string;
  toNoteId?: string;
}
