/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoteRequestDto {
  color?: string;
  content?: string;
  height?: number;
  noteType?: NoteType;
  positionX?: number;
  positionY?: number;
  width?: number;
}

export type NoteType =
  | "STICKY"
  | "PHOTO"
  | "DOCUMENT"
  | "CLIPPING"
  | "LABEL"
  | "INDEX_CARD"
  | "EVIDENCE_TAG";
