/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoteRequestDto {
  color?: string;
  content?: string;
  height?: number;
  noteType?: string;
  positionX?: number;
  positionY?: number;
  width?: number;
}
