/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoteResponseDto {
  color?: string;
  content?: string;
  createdDate?: string;
  id?: string;
  imageUrl?: string;
  positionX?: number;
  positionY?: number;
}
