/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BoardResponseDto } from '../../models/board-response-dto';

export interface GetBoards$Params {
}

export function getBoards(http: HttpClient, rootUrl: string, params?: GetBoards$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BoardResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getBoards.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BoardResponseDto>>;
    })
  );
}

getBoards.PATH = '/api/v1/boards';
