/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LinkResponse } from '../../models/link-response';

export interface GetLinkById$Params {
  boardId: string;
  linkId: string;
}

export function getLinkById(http: HttpClient, rootUrl: string, params: GetLinkById$Params, context?: HttpContext): Observable<StrictHttpResponse<LinkResponse>> {
  const rb = new RequestBuilder(rootUrl, getLinkById.PATH, 'get');
  if (params) {
    rb.path('boardId', params.boardId, {});
    rb.path('linkId', params.linkId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LinkResponse>;
    })
  );
}

getLinkById.PATH = '/api/v1/boards/{boardId}/links/{linkId}';
