/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LinkResponse } from '../../models/link-response';
import { UpdateLinkRequest } from '../../models/update-link-request';

export interface PatchLink$Params {
  boardId: string;
  linkId: string;
      body: UpdateLinkRequest
}

export function patchLink(http: HttpClient, rootUrl: string, params: PatchLink$Params, context?: HttpContext): Observable<StrictHttpResponse<LinkResponse>> {
  const rb = new RequestBuilder(rootUrl, patchLink.PATH, 'patch');
  if (params) {
    rb.path('boardId', params.boardId, {});
    rb.path('linkId', params.linkId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LinkResponse>;
    })
  );
}

patchLink.PATH = '/api/v1/boards/{boardId}/links/{linkId}';
